### ISSUE TITLE
能否考虑支持文字水印

### ISSUE THREAD

**Issue by jonnywang** [exinnet/tclip#5]
能否考虑支持文字水印？

putText(dest_image, "xingqiba" , Point(10, dest_image.rows-20), CV_FONT_HERSHEY_SIMPLEX, 0.8f, CV_RGB(255,255,255), 2);
![a1_](https://cloud.githubusercontent.com/assets/960982/10391777/d5d1a770-6eb3-11e5-9ab1-d248518574d9.jpg) [demo](https://github.com/jonnywang/tclip)

**Comment by jonnywang** [comment]
能否考虑支持opencv3

mac上opencv 2.4.4编译通不过

**Comment by exinnet** [comment]
可以支持。最近忙双十一的准备，可能没时间。双十一过后。进行下完善。

**Comment by exinnet** [comment]
已经合并到master。提供了基本的水印功能。之后可以提供更多的可选参数，控制水印效果。
